USE [master]
GO
/****** Object:  Database [EmailAuth]    Script Date: 15/05/2022 4:34:19 PM ******/
CREATE DATABASE [EmailAuth]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmailAuth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EmailAuth.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EmailAuth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\EmailAuth_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [EmailAuth] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmailAuth].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EmailAuth] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EmailAuth] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EmailAuth] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EmailAuth] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EmailAuth] SET ARITHABORT OFF 
GO
ALTER DATABASE [EmailAuth] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EmailAuth] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EmailAuth] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EmailAuth] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EmailAuth] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EmailAuth] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EmailAuth] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EmailAuth] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EmailAuth] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EmailAuth] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EmailAuth] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EmailAuth] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EmailAuth] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EmailAuth] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EmailAuth] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EmailAuth] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EmailAuth] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EmailAuth] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EmailAuth] SET  MULTI_USER 
GO
ALTER DATABASE [EmailAuth] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EmailAuth] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EmailAuth] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EmailAuth] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [EmailAuth] SET DELAYED_DURABILITY = DISABLED 
GO
USE [EmailAuth]
GO
/****** Object:  Table [dbo].[tokens]    Script Date: 15/05/2022 4:34:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tokens](
	[token_id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[token] [varchar](128) NOT NULL,
 CONSTRAINT [PK_tokens] PRIMARY KEY CLUSTERED 
(
	[token_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[users]    Script Date: 15/05/2022 4:34:19 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[user_id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](64) NOT NULL,
	[password] [varchar](128) NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[tokens]  WITH CHECK ADD  CONSTRAINT [FK_tokens_users] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO
ALTER TABLE [dbo].[tokens] CHECK CONSTRAINT [FK_tokens_users]
GO
USE [master]
GO
ALTER DATABASE [EmailAuth] SET  READ_WRITE 
GO
